# Generated by Django 5.0.6 on 2024-05-31 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='promocode_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='toys.promocode'),
        ),
    ]
