# Generated by Django 5.0.6 on 2024-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_promocode_sale_promocode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promocode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
