# Generated by Django 5.1 on 2024-09-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_sale_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('logo', models.ImageField(blank=True, default='product_images/FCxARCPWYAEi9ux.jpg', null=True, upload_to='product_images/')),
                ('setrificate', models.ImageField(blank=True, default='product_images/FCxARCPWYAEi9ux.jpg', null=True, upload_to='product_images/')),
                ('text', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendCompanies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='product_images/FCxARCPWYAEi9ux.jpg', null=True, upload_to='product_images/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.product')),
            ],
        ),
    ]
