# Generated by Django 5.0.6 on 2024-05-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admin_remove_user_is_admin_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adult',
        ),
    ]
