# Generated by Django 5.0.6 on 2024-05-22 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_is_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, default='employee_images/photo_2023-12-03_02-14-05.jpg', null=True, upload_to='employee_images/'),
        ),
        migrations.AddField(
            model_name='admin',
            name='position',
            field=models.CharField(default='MAIN ADMIN', max_length=200),
        ),
        migrations.AddField(
            model_name='admin',
            name='salary',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
